#!/usr/bin/with-contenv bash

# use var ${APP} define is Dockerfile to start app
# /bin/s6-notifyoncheck -d
# s6-setuidgid abc

# Use s6 or not. To use add: s6-setuidgid leave black to not use
USE_S6=s6-setuidgid

# 1 or 0 to use or not
#APP_DEBUGMODE=0

#use var ${APP} to strat app
# /bin/s6-notifyoncheck -d
# s6-setuidgid abc
#exec \
#	s6-setuidgid abc ${APP} 

#cd /storage
if [ "${APP_DEBUGMODE}" -eq 1 ]; then
  exec $USE_S6 $APP_PATH abc ${START_APP1} ${APP_ARGS1} >> ${APP_LOG}
else
  exec $USE_S6 $APP_PATH abc ${START_APP1} ${APP_ARGS1}
fi