#!/usr/bin/with-contenv bash

mkdir -p /config/grafana/{conf,data/plugins,log}
mkdir -p /config/influxdb/{data,meta,wal,logs} \
	&& mkdir -p /config/telegraf \
    && rm -f /config/influxdb/influxd.pid \
    && rm -f /config/influxdb/influxd.log \
    #&& cp -n /influxdb.conf /config/influxdb/

# if exists
if [ ! -f /config/influxdb/influxdb.conf ]; then
echo "influxdb not found in config folder... copying it from /temp. This is normal when you start this container for the first time"
cp -R /temp/influxdb /config
else
echo "influxdb.conf exists.."
fi

# if exists
if [ ! -f /config/telegraf/telegraf.conf ]; then
echo "telegraf.conf not found in config folder.. copying it from /temp. This is normal when you start this container for the first time"
cp -R /temp/telegraf /config
else
echo "telegraf.conf exists.."
fi

#sed -i "s|:8086|:$INFLUXDB_HTTP_PORT|g" '/config/influxdb/influxdb.conf'
#sed -i "s|:8088|:$INFLUXDB_RPC_PORT|g" '/config/influxdb/influxdb.conf'
echo '[info] influxdb fixed.'

# if exists
if [ ! -f /config/grafana/grafana.ini ]; then
echo "not exists"
#cp -R /usr/share/grafana/conf /config/grafana

cp /temp/grafana.ini /config/grafana/grafana.ini
cp -R /usr/share/grafana/conf/provisioning /config/grafana/conf
cp -R /usr/share/grafana/conf/defaults.ini /config/grafana/conf/defaults.ini
#cp -R /usr/share/grafana/public /config/grafana/public
ln -s /usr/share/grafana/public /config/grafana/public
else
echo "grafana defaults.ini exists"
fi	

echo "#########################"
echo "Check /config for log files."
echo "#########################"

# if exists
#if [ ! -f /config/www/noVNC/vnc.html ]; then
#echo "not exists"
#cp -R /somedir /some/dir
#else
#echo " exists"
#fi	

# fix permissions
chown -R abc:abc \
	/config \
	/var/lib/influxdb \

# clean temp folder
rm -rf /temp